
language:
  - php

dist:
  - trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
      dist: precise
      env: PHP56=true
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
      env: HHVM=true
  allow_failures:
    - php: hhvm
    - php: nightly
    - script: vendor/bin/phpcs

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --optimize-autoloader
  - if [[ $PHP56 == true ]]; then composer require "phpunit/phpunit:5.7"; fi
  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
